[project]
name = "catalogo-de-jogos"
version = "0.1.0"
description = ""
authors = [
    {name = "saviocunha",email = "savio.cunha@aluno.ufca.edu.br"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "catalogo_de_jogos", from = "src"}]

[tool.pytest.ini_options]
pythonpath = "src"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
